#!/bin/sh

#
# runs prettier on staged js,json,scss files before the commit
#
# copy this to .git/hooks/pre-commit
# chmod +x ./git/hooks/pre-commit
#

# if anything fails, stop the commit
set -e

jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|scss|json)$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

# Prettify all staged .js files
echo "$jsfiles" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$jsfiles" | xargs git add

exit 0
